import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime.js';

dayjs.extend(relativeTime);

export function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return str.slice(0, maxLength - 3) + '...';
}

export function formatDate(isoDate: string): string {
  return dayjs(isoDate).format('MMM D, YYYY h:mm A');
}

export function formatShortDate(isoDate: string | Date): string {
  return dayjs(isoDate).format('MMM D');
}

export function formatRelativeDate(isoDate: string | Date): string {
  return dayjs(isoDate).fromNow();
}

export function stripSystemTags(text: string): string {
  return text
    .replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, '')
    .replace(/<command-message>[\s\S]*?<\/command-message>/g, '')
    .replace(/<command-name>[\s\S]*?<\/command-name>/g, '')
    .replace(/<command-args>[\s\S]*?<\/command-args>/g, '')
    .trim();
}

/**
 * Generate a clean, readable title for a session.
 * Priority: custom name > summary > cleaned firstPrompt > branch-derived title
 */
export function cleanSessionTitle(session: {
  name: string | null;
  summary: string;
  firstPrompt: string;
  branch: string;
}): string {
  // Custom name is always best
  if (session.name) return session.name;

  // Summary from sessions-index.json (AI-generated by Claude Code)
  if (session.summary && !isJunkText(session.summary)) {
    return session.summary;
  }

  // Clean the first prompt
  const cleaned = stripSystemTags(session.firstPrompt)
    .replace(/^Base directory for this skill:[\s\S]*/i, '')
    .replace(/^#.*\n/gm, '')
    .trim();

  if (cleaned && cleaned.length > 5 && !isJunkText(cleaned)) {
    // Take first line only, cap it
    const firstLine = cleaned.split('\n')[0].trim();
    return firstLine.length > 60
      ? firstLine.slice(0, 57) + '...'
      : firstLine;
  }

  // Fall back to branch name → human readable
  if (session.branch) {
    return branchToTitle(session.branch);
  }

  return 'Untitled Session';
}

function isJunkText(text: string): boolean {
  return (
    text.startsWith('Base directory') ||
    text.startsWith('<!') ||
    text.startsWith('<command') ||
    text.startsWith('<system') ||
    text.length < 3
  );
}

function branchToTitle(branch: string): string {
  // fix/2190-trusted-device-wrongtype-redis → Trusted Device Wrongtype Redis
  return branch
    .replace(/^(fix|feature|refactor|chore|docs|security|hotfix)\//, '')
    .replace(/^\d+-/, '')
    .replace(/[-_]/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();
}

export function cleanMessageContent(content: unknown): string {
  if (typeof content === 'string') {
    return stripSystemTags(content);
  }
  if (Array.isArray(content)) {
    return content
      .filter(
        (block: Record<string, unknown>) =>
          block.type === 'text' && typeof block.text === 'string',
      )
      .map((block: Record<string, unknown>) => block.text as string)
      .join('\n');
  }
  return '';
}
